# Generated by Django 3.1.2 on 2020-10-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201007_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='deleted',
            new_name='Approved',
        ),
    ]
